//
// Created by Guillaume on 14/04/2017.
//

#ifndef VULKAN_BASICCONFIGURATION_HH
#define VULKAN_BASICCONFIGURATION_HH

const int WIDTH = 800;
const int HEIGHT = 600;

#endif //VULKAN_BASICCONFIGURATION_HH
